-- Query 1: Find the item that has the minimum weight
SELECT ITEMNO, DESCRIPTION, WEIGHT, COST
FROM ITEMS
WHERE WEIGHT = (SELECT MIN(WEIGHT) FROM ITEMS);

-- Query 2: Find the different warehouses in "PUNE"
SELECT DISTINCT WAREHOUSES.WNAME
FROM WAREHOUSES
JOIN CITIES ON WAREHOUSES.CITY = CITIES.CITY
WHERE CITIES.CITY = 'PUNE';
